// AI: purpose=Drum candidate type for operator-generated events; consumed by selection engine and mapped to GrooveOnset.
// AI: invariants=BarNumber>=1; Beat>=1.0; Score in 0.0-1.0; CandidateId is deterministic for same inputs; Role is valid drum role.
// AI: deps=OnsetStrength from Groove.cs; FillRole and DrumArticulation enums; consumed by OperatorSelectionEngine and DrumCandidateMapper.
// AI: change=Story 2.2; extend with additional hint fields as operators require; keep immutable record.


using Music.Generator.Groove;

namespace Music.Generator.Agents.Drums
{
    /// <summary>
    /// Represents a drum event candidate generated by an operator.
    /// Contains rich metadata about the intended hit including position, strength, velocity/timing hints,
    /// articulation, fill role, and operator-assigned score.
    /// Story 2.2: Define Drum Candidate Type.
    /// </summary>
    public sealed record DrumCandidate
    {
        /// <summary>
        /// Stable identifier for this candidate: operatorId + position + distinguishing params.
        /// Format: "{OperatorId}_{Role}_{BarNumber}_{Beat}" with optional suffix for articulation.
        /// Used for deduplication, diagnostics, and deterministic tie-breaking.
        /// </summary>
        public required string CandidateId { get; init; }

        /// <summary>
        /// Identifier of the operator that generated this candidate.
        /// Used for diagnostics, memory tracking, and style weight lookup.
        /// </summary>
        public required string OperatorId { get; init; }

        /// <summary>
        /// Drum role for this hit (Kick, Snare, ClosedHat, OpenHat, Crash, Ride, Tom1, Tom2, FloorTom).
        /// </summary>
        public required string Role { get; init; }

        /// <summary>
        /// Bar number (1-based) in the song.
        /// </summary>
        public required int BarNumber { get; init; }

        /// <summary>
        /// Beat position (1-based) within the bar. Can be fractional (e.g., 1.5, 2.75).
        /// </summary>
        public required decimal Beat { get; init; }

        /// <summary>
        /// Onset strength classification (Downbeat, Backbeat, Strong, Offbeat, Pickup, Ghost).
        /// Guides velocity shaping and accent patterns.
        /// </summary>
        public required OnsetStrength Strength { get; init; }

        /// <summary>
        /// Operator-suggested velocity (0-127). Nullable: when null, velocity shaper computes from strength/role.
        /// </summary>
        public int? VelocityHint { get; init; }

        /// <summary>
        /// Operator-suggested timing offset in ticks (positive = late, negative = early).
        /// Nullable: when null, timing shaper computes from role/style defaults.
        /// </summary>
        public int? TimingHint { get; init; }

        /// <summary>
        /// Articulation hint for the hit (Rimshot, SideStick, OpenHat, etc.).
        /// Nullable: when null, uses standard articulation for the role.
        /// </summary>
        public DrumArticulation? ArticulationHint { get; init; }

        /// <summary>
        /// Fill role classification (None, Setup, FillStart, FillBody, FillEnd).
        /// Used by fill operators to mark candidate intent and by memory system for fill shape tracking.
        /// </summary>
        public required FillRole FillRole { get; init; }

        /// <summary>
        /// Operator-assigned score (0.0-1.0) before style weighting and memory penalties.
        /// Higher scores indicate more musically relevant candidates.
        /// </summary>
        public required double Score { get; init; }

        /// <summary>
        /// Creates a minimal DrumCandidate for testing purposes.
        /// </summary>
        public static DrumCandidate CreateMinimal(
            string operatorId = "TestOperator",
            string role = GrooveRoles.Snare,
            int barNumber = 1,
            decimal beat = 2.0m,
            OnsetStrength strength = OnsetStrength.Backbeat,
            double score = 0.5)
        {
            string candidateId = $"{operatorId}_{role}_{barNumber}_{beat}";
            return new DrumCandidate
            {
                CandidateId = candidateId,
                OperatorId = operatorId,
                Role = role,
                BarNumber = barNumber,
                Beat = beat,
                Strength = strength,
                VelocityHint = null,
                TimingHint = null,
                ArticulationHint = null,
                FillRole = FillRole.None,
                Score = score
            };
        }

        /// <summary>
        /// Generates a deterministic CandidateId from the provided parameters.
        /// </summary>
        public static string GenerateCandidateId(
            string operatorId,
            string role,
            int barNumber,
            decimal beat,
            DrumArticulation? articulation = null)
        {
            var baseId = $"{operatorId}_{role}_{barNumber}_{beat}";
            if (articulation.HasValue && articulation.Value != DrumArticulation.None)
            {
                return $"{baseId}_{articulation.Value}";
            }
            return baseId;
        }

        /// <summary>
        /// Validates that this candidate has valid field values.
        /// Returns true if valid; otherwise returns false with error message.
        /// </summary>
        public bool TryValidate(out string? errorMessage)
        {
            if (BarNumber < 1)
            {
                errorMessage = $"BarNumber must be >= 1, was {BarNumber}";
                return false;
            }

            if (Beat < 1.0m)
            {
                errorMessage = $"Beat must be >= 1.0, was {Beat}";
                return false;
            }

            if (Score < 0.0 || Score > 1.0)
            {
                errorMessage = $"Score must be in [0.0, 1.0], was {Score}";
                return false;
            }

            if (VelocityHint.HasValue && (VelocityHint.Value < 0 || VelocityHint.Value > 127))
            {
                errorMessage = $"VelocityHint must be in [0, 127], was {VelocityHint.Value}";
                return false;
            }

            if (string.IsNullOrWhiteSpace(OperatorId))
            {
                errorMessage = "OperatorId cannot be null or whitespace";
                return false;
            }

            if (string.IsNullOrWhiteSpace(Role))
            {
                errorMessage = "Role cannot be null or whitespace";
                return false;
            }

            if (string.IsNullOrWhiteSpace(CandidateId))
            {
                errorMessage = "CandidateId cannot be null or whitespace";
                return false;
            }

            errorMessage = null;
            return true;
        }
    }
}
